package main

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// Flash images embedded at build time.
// CI copies these from PlatformIO build output before `go build`.
//
//go:embed embed/bootloader.bin
var embeddedBootloader []byte

//go:embed embed/partitions.bin
var embeddedPartitions []byte

//go:embed embed/boot_app0.bin
var embeddedOTAData []byte

//go:embed embed/firmware.bin
var embeddedFirmware []byte

// Flash offsets generated by CI from PlatformIO's idedata.json.
//
//go:embed embed/offsets.json
var embeddedOffsets []byte

// Ensure embed package is referenced
var _ embed.FS

type flashOffsets struct {
	Bootloader string `json:"bootloader"`
	Partitions string `json:"partitions"`
	OTAData    string `json:"otadata"`
	App        string `json:"app"`
}

const esptoolVersion = "v5.2.0"

// progressReader wraps an io.Reader and prints download progress.
type progressReader struct {
	r       io.Reader
	total   int64
	current int64
	lastPct int
}

func (pr *progressReader) Read(p []byte) (int, error) {
	n, err := pr.r.Read(p)
	pr.current += int64(n)
	pct := int(float64(pr.current) / float64(pr.total) * 100)
	if pct != pr.lastPct {
		pr.lastPct = pct
		bar := pct / 2
		fmt.Printf("\r  [%-50s] %d%%", strings.Repeat("#", bar)+strings.Repeat(".", 50-bar), pct)
	}
	return n, err
}

// findEsptool looks for esptool in PATH or in the cache directory.
func findEsptool() (string, error) {
	for _, name := range []string{"esptool", "esptool.py"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}

	cached := cachedEsptoolPath()
	if _, err := os.Stat(cached); err == nil {
		return cached, nil
	}

	return "", fmt.Errorf("esptool not found")
}

func cachedEsptoolPath() string {
	cacheDir, _ := os.UserCacheDir()
	name := "esptool"
	if runtime.GOOS == "windows" {
		name = "esptool.exe"
	}
	return filepath.Join(cacheDir, "openneato", esptoolVersion, name)
}

// downloadEsptool downloads the esptool binary from GitHub releases.
func downloadEsptool() (string, error) {
	url := esptoolDownloadURL()
	if url == "" {
		return "", fmt.Errorf("no esptool binary available for %s/%s", runtime.GOOS, runtime.GOARCH)
	}

	dest := cachedEsptoolPath()
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return "", err
	}

	resp, err := http.Get(url) //nolint:gosec
	if err != nil {
		return "", fmt.Errorf("download esptool: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("download esptool: HTTP %d", resp.StatusCode)
	}

	size := resp.ContentLength
	if size > 0 {
		fmt.Printf("Downloading esptool %s (%.1f MB)...\n", esptoolVersion, float64(size)/1024/1024)
	} else {
		fmt.Printf("Downloading esptool %s...\n", esptoolVersion)
	}

	body := io.Reader(resp.Body)
	if size > 0 {
		body = &progressReader{r: resp.Body, total: size}
	}

	if strings.HasSuffix(url, ".zip") {
		err = extractZip(body, dest)
	} else {
		err = extractTarGz(body, dest)
	}
	if err == nil {
		fmt.Printf("\r  [%-50s] 100%%\n", strings.Repeat("#", 50))
	} else {
		fmt.Println()
	}
	if err != nil {
		return "", fmt.Errorf("extract esptool: %w", err)
	}

	fmt.Printf("Installed esptool to %s\n", dest)
	return dest, nil
}

func esptoolDownloadURL() string {
	base := fmt.Sprintf("https://github.com/espressif/esptool/releases/download/%s/esptool-%s", esptoolVersion, esptoolVersion)
	switch runtime.GOOS + "/" + runtime.GOARCH {
	case "darwin/arm64":
		return base + "-macos-arm64.tar.gz"
	case "darwin/amd64":
		return base + "-macos-amd64.tar.gz"
	case "linux/amd64":
		return base + "-linux-amd64.tar.gz"
	case "linux/arm64":
		return base + "-linux-aarch64.tar.gz"
	case "windows/amd64":
		return base + "-windows-amd64.zip"
	default:
		return ""
	}
}

func extractTarGz(r io.Reader, dest string) error {
	gz, err := gzip.NewReader(r)
	if err != nil {
		return err
	}
	defer func() { _ = gz.Close() }()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		if filepath.Base(hdr.Name) == "esptool" && hdr.Typeflag == tar.TypeReg {
			f, err := os.OpenFile(dest, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o755)
			if err != nil {
				return err
			}
			_, err = io.Copy(f, tr) //nolint:gosec
			_ = f.Close()
			return err
		}
	}
	return fmt.Errorf("esptool binary not found in archive")
}

func extractZip(r io.Reader, dest string) error {
	tmp, err := os.CreateTemp("", "esptool-*.zip")
	if err != nil {
		return err
	}
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmp.Name())
	}()

	size, err := io.Copy(tmp, r)
	if err != nil {
		return err
	}

	zr, err := zip.NewReader(tmp, size)
	if err != nil {
		return err
	}

	for _, f := range zr.File {
		if filepath.Base(f.Name) == "esptool.exe" {
			rc, err := f.Open()
			if err != nil {
				return err
			}
			out, err := os.OpenFile(dest, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o755)
			if err != nil {
				_ = rc.Close()
				return err
			}
			_, err = io.Copy(out, rc) //nolint:gosec
			_ = rc.Close()
			_ = out.Close()
			return err
		}
	}
	return fmt.Errorf("esptool.exe not found in archive")
}

// flashFirmware writes embedded images to a temp dir and invokes esptool
// with offsets read from the embedded offsets.json.
func flashFirmware(portName string, esptoolPath string) error {
	var offsets flashOffsets
	if err := json.Unmarshal(embeddedOffsets, &offsets); err != nil {
		return fmt.Errorf("parse offsets: %w", err)
	}

	tmp, err := os.MkdirTemp("", "openneato-flash-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer func() { _ = os.RemoveAll(tmp) }()

	type image struct {
		data   []byte
		offset string
		name   string
	}

	images := []image{
		{embeddedBootloader, offsets.Bootloader, "bootloader.bin"},
		{embeddedPartitions, offsets.Partitions, "partitions.bin"},
		{embeddedOTAData, offsets.OTAData, "boot_app0.bin"},
		{embeddedFirmware, offsets.App, "firmware.bin"},
	}

	args := []string{
		"-p", portName,
		"-b", "921600",
		"--before", "default-reset",
		"--after", "hard-reset",
		"write-flash", "-z",
	}

	for _, img := range images {
		path := filepath.Join(tmp, img.name)
		if err := os.WriteFile(path, img.data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", img.name, err)
		}
		fmt.Printf("  %s: %d bytes at %s\n", img.name, len(img.data), img.offset)
		args = append(args, img.offset, path)
	}

	fmt.Printf("Flashing via %s...\n", esptoolPath)

	cmd := exec.Command(esptoolPath, args...) //nolint:gosec
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("esptool failed: %w", err)
	}

	return nil
}
